repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.39.4
    hooks:
      - id: basedpyright