name: Bug Report
description: Report a bug or unexpected behavior in aioscraper
labels: ["potential bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: "When I try to... the following happens..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal code example to reproduce the issue.
      placeholder: |
        from aioscraper import AIOScraper, Request, Response, SendRequest

        scraper = AIOScraper()

        @scraper
        async def scrape(send_request: SendRequest):
            # Your code here
            pass
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: "I expected the scraper to..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: "Instead, the scraper..."
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If applicable, paste the full error traceback.
      placeholder: |
        Traceback (most recent call last):
          File "...", line ..., in ...
        ...
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: aioscraper version
      description: "Output of: `pip show aioscraper | grep Version`"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "Output of: `python --version`"
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: http-backend
    attributes:
      label: HTTP Backend
      description: Which HTTP backend are you using?
      options:
        - aiohttp
        - httpx
        - both
        - not sure
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: "e.g., Ubuntu 22.04, macOS 14.1, Windows 11"
      placeholder: "Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "Output of: `pip list | grep -E '(aioscraper|aiohttp|httpx|aiojobs)'`"
      placeholder: |
        aioscraper    0.1.0
        aiohttp       3.9.0
        aiojobs       1.2.0
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: If using custom configuration, paste relevant parts.
      placeholder: |
        SessionConfig(
            rate_limit=RateLimitConfig(...)
        )
      render: python
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots that might help.
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you found a workaround, please share it.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version of aioscraper
          required: true
        - label: I have provided a minimal reproducible example
          required: true
